"use client";
import { useEffect, useState } from "react";

const services = [
["01","Sistemas industriais sob medida","Aplicações construídas para o seu fluxo real, sem forçar a operação a caber em um software genérico."],
["02","Integrações & middleware","Conectamos sistemas, equipamentos e dados para eliminar ilhas de informação e trabalho manual."],
["03","Automação operacional","Rotinas confiáveis para acelerar processos, reduzir retrabalho e dar previsibilidade à produção."],
["04","Rastreabilidade & serialização","Controle de eventos e registros para operações que exigem histórico, precisão e conformidade."],
["05","Integração com equipamentos","Comunicação com impressoras, leitores, câmeras e dispositivos já presentes no chão de fábrica."],
["06","Aplicações desktop & serviços","Soluções Windows e serviços de retaguarda preparados para ambientes críticos e operação contínua."]
];
const segments=[["PRD","Produção","Fluxos produtivos, apontamentos e controle operacional."],["LOG","Logística","Movimentação, leitura, identificação e expedição."],["QLD","Qualidade","Rastreabilidade, registros e evidências do processo."],["INT","Integração","Sistemas legados, ERPs, APIs e equipamentos."]];
const steps=[["01","Entender","Mapeamos a operação, os riscos e o resultado que precisa ser alcançado."],["02","Projetar","Desenhamos a solução e as integrações com escopo claro e decisões compartilhadas."],["03","Construir","Desenvolvemos em ciclos curtos, com validações frequentes junto à sua equipe."],["04","Implantar","Colocamos em operação com cuidado, documentação e acompanhamento próximo."]];

export default function Home(){
 const [open,setOpen]=useState(false); const [scrolled,setScrolled]=useState(false);
 useEffect(()=>{const u=()=>setScrolled(scrollY>24);u();addEventListener("scroll",u);return()=>removeEventListener("scroll",u)},[]);
 return <main>
  <header className={scrolled?"header scrolled":"header"}><a className="brand" href="#inicio"><span>D2</span>CODE</a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Abrir menu"><i/><i/></button><nav className={open?"open":""}><a href="#servicos">Serviços</a><a href="#segmentos">Atuação</a><a href="#sobre">Sobre</a><a href="#processo">Processo</a><a className="navcta" href="#contato">Falar com a D2</a></nav></header>
  <section className="hero" id="inicio"><div className="grid"/><div className="container hero-in"><div><p className="eyebrow">Software industrial sob medida</p><h1>Software conectado à <em>realidade da operação.</em></h1><p className="lead">Sistemas, integrações e automações que transformam processos complexos em operações mais estáveis, rastreáveis e eficientes.</p><div className="actions"><a className="button" href="#contato">Converse sobre seu projeto ↗</a><a href="#servicos">Conheça nossas soluções ↓</a></div></div><div className="diagram"><p>OPERAÇÃO CONECTADA <b>● ONLINE</b></p><article className="n1">01 <strong>Equipamentos</strong><small>Leitores · Câmeras · Impressoras</small></article><article className="n2">02 <strong>D2 Middleware</strong><small>Integração · Regras · Dados</small></article><article className="n3">03 <strong>Sistemas</strong><small>ERP · MES · Aplicações</small></article></div></div><div className="strip"><div className="container"><span>Desenvolvimento sob medida</span><span>Integração industrial</span><span>Rastreabilidade</span><span>Automação de processos</span></div></div></section>
  <section className="section intro"><div className="container heading"><div><small>[ 01 ]</small><p className="eyebrow blue">Nossa proposta</p></div><div><h2>Tecnologia que se adapta à sua operação — <em>não o contrário.</em></h2><p>Entramos onde soluções prontas param. Entendemos o processo, conectamos o que já existe e desenvolvemos exatamente o que a operação precisa para avançar com segurança.</p></div></div><div className="container values">{[["01","Feito para o seu processo","Cada solução parte da rotina, das restrições e dos objetivos reais da sua equipe."],["02","Integração de ponta a ponta","Software, dispositivos e sistemas trabalhando juntos em um fluxo consistente."],["03","Estabilidade em primeiro lugar","Arquitetura pensada para ambientes onde parar não é uma opção."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section className="section dark" id="servicos"><div className="container heading"><div><small>[ 02 ]</small><p className="eyebrow">O que fazemos</p></div><h2>Da necessidade operacional à <em>solução em produção.</em></h2></div><div className="container service-list">{services.map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><i>↗</i></article>)}</div></section>
  <section className="section" id="segmentos"><div className="container heading"><div><small>[ 03 ]</small><p className="eyebrow blue">Onde atuamos</p></div><h2>Soluções para os pontos críticos da <em>cadeia operacional.</em></h2></div><div className="container segments">{segments.map(x=><article key={x[0]}><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div><div className="container band"><small>AMBIENTES EM QUE FAZEMOS A DIFERENÇA</small><div>Chão de fábrica · Operações críticas · Ambientes regulados · Processos legados</div></div></section>
  <section className="section about" id="sobre"><div className="container about-in"><div className="visual"><pre><span>const</span> operacao = &#123;{"\n"}  estavel: <b>true</b>,{"\n"}  integrada: <b>true</b>,{"\n"}  sobMedida: <b>true</b>{"\n"}&#125;;</pre><div><strong>D2</strong><small>DESIGN<br/>+ DEVELOPMENT</small></div></div><div><small>[ 04 ]</small><p className="eyebrow">Sobre a D2 Code</p><h2>Experiência técnica com visão de <em>operação.</em></h2><p>A D2 Code é uma empresa de Atibaia especializada em desenvolvimento de software para ambientes industriais e produtivos. Criamos soluções que conversam com equipamentos, sistemas e processos já existentes — respeitando a realidade de cada cliente.</p><p>Nosso foco é entregar tecnologia confiável, compreensível e útil no dia a dia: da primeira conversa à solução funcionando.</p><div className="facts"><b>2025 <small>Fundação</small></b><b>Atibaia · SP <small>Base de operação</small></b><b>Sob medida <small>Modelo de entrega</small></b></div></div></div></section>
  <section className="section" id="processo"><div className="container heading"><div><small>[ 05 ]</small><p className="eyebrow blue">Como trabalhamos</p></div><h2>Clareza do primeiro diagnóstico à <em>entrada em operação.</em></h2></div><div className="container process">{steps.map(x=><article key={x[0]}><b>{x[0]}</b><i/><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section className="cta" id="contato"><div className="grid"/><div className="container"><p className="eyebrow">Vamos conversar</p><h2>Existe um processo travando sua operação?</h2><p>Conte o desafio. A gente ajuda a transformar complexidade em uma solução que funciona.</p><a className="button" target="_blank" rel="noreferrer" href="https://www.linkedin.com/company/d2code">Falar com a D2 Code no LinkedIn ↗</a><small>Atendimento a empresas · Atibaia, SP e projetos em todo o Brasil</small></div></section>
  <footer><div className="container foot"><a className="brand" href="#inicio"><span>D2</span>CODE</a><p>Software industrial conectado<br/>à realidade da operação.</p><div><a href="https://www.linkedin.com/company/d2code">LinkedIn ↗</a><a href="https://d2code.com.br">d2code.com.br ↗</a></div></div><div className="container copy">© {new Date().getFullYear()} D2 Code Sistemas Ltda. <a href="#inicio">Voltar ao topo ↑</a></div></footer>
 </main>
}
